// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vchgdgnnemyzmshejmen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjaGdkZ25uZW15em1zaGVqbWVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5Njk4NzIsImV4cCI6MjA2OTU0NTg3Mn0.Rh2OC_KgzgZxmC-J1MUBZ1H_NVm_QpWumxG5_ufDcmE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'X-Client-Info': 'verse-builder@1.0.0',
    },
  }
});